### ISSUE TITLE
فرمت EPUB

### ISSUE THREAD

**Issue by xmha97** [ganjoor/ganjoor-tex#2]
سلام
اشعار را از آدرس زیر با فرمت EPub دانلود کردم:
http://epub.ganjoor.net/

اما هیچ‌کدام متادیتا (تگ) ندارند، حتی کاور هم ندارند.

![image](https://user-images.githubusercontent.com/23485114/210476527-c214db47-2382-4f60-aed0-cd84009189ef.png)

من از نرم افزار کالیبر استفاده می‌کنم:
https://calibre-ebook.com/

**Comment by r-shf** [comment]
سلام. لطفا مشکل را از طریق آدرس ایمیل گنجور اطلاع بدهید.
